/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique ID from Halilit (SKU)
 */
export type HalilitId = string;
/**
 * Name as listed on Halilit
 */
export type ProductName = string;
/**
 * Brand as listed on Halilit
 */
export type Brand = string;
/**
 * Official IL Price from Halilit
 */
export type PriceIl = number;
/**
 * Official Eilat Price from Halilit
 */
export type PriceEilat = number;
/**
 * Source URL on Halilit
 */
export type HalilitUrl = string;
export type Sku = string | null;
export type ModelNumber = string | null;
export type OfficialName = string | null;
/**
 * Marketing copy from brand site
 */
export type OfficialDescription = string | null;
export type Type = string;
export type Url = string;
export type DisplayPurpose = string;
export type Resolution = string | null;
/**
 * Confidence level in data source
 */
export type DataSourceConfidence = 'official' | 'trusted' | 'commercial' | 'user' | 'inferred';
export type AltText = string | null;
export type Priority = number;
/**
 * High-res assets from brand
 */
export type OfficialImages = MediaAsset[];
/**
 * URL of the official product page
 */
export type OfficialUrl = string | null;
/**
 * Reviews from trusted sites
 */
export type Reviews = {
  [k: string]: unknown;
}[];
/**
 * AI summary of pros/cons
 */
export type ReviewSynthesis = string | null;
/**
 * Normalized 0-5 rating
 */
export type AverageRating = number | null;
/**
 * Status throughout the ingestion workflow
 */
export type IngestionStatus = 'harvested' | 'enriched' | 'validated' | 'approved' | 'rejected' | 'archived';
export type PipelinePhase = string;
export type CreatedAt = string;
export type LastUpdated = string;
export type CanonicalCategory = string;
export type CanonicalSubcategory = string;
export type BrandTaxonomy = string | null;
export type AltCategories = string[];
export type Keywords = string[];
export type PriceIl1 = number;
export type PriceEilat1 = number;
export type PriceUsd = number | null;
export type PriceEur = number | null;
/**
 * Standard pricing tier categories
 */
export type PricingTier = 'entry' | 'mid' | 'pro' | 'flagship' | 'legacy';
export type EilatDiscountPercent = number;
/**
 * Standard pricing tier categories
 */
export type PricingTier1 = 'entry' | 'mid' | 'pro' | 'flagship' | 'legacy';
export type PriceValidityMarker = string;
export type LastPriceChange = string | null;
export type PreviousPriceIl = number | null;
/**
 * Primary purpose of product for UI display
 */
export type DisplayRole = 'hero' | 'cornerstone' | 'specialist' | 'entry' | 'hidden';
export type HeroImage = string | null;
export type ThumbnailImage = string | null;
export type ShouldHighlight = boolean;
export type DisplayTierLevel = number;
export type ColorHint = string | null;
export type MediaAssets = MediaAsset[];
/**
 * Confidence level in data source
 */
export type DataSourceConfidence1 = 'official' | 'trusted' | 'commercial' | 'user' | 'inferred';
export type SpecsCompleteness = number;
export type SpecsMarkdown = string | null;
export type DescriptionShort = string | null;
export type DescriptionLong = string | null;
export type FeatureList = string[];
export type SourceName = string;
export type SourceUrl = string;
/**
 * Confidence level in data source
 */
export type DataSourceConfidence2 = 'official' | 'trusted' | 'commercial' | 'user' | 'inferred';
export type Timestamp = string;
export type ExtractionMethod = string;
export type ExtractionNotes = string | null;
export type Sources = SourceProvenance[];
export type FieldName = string;
export type Source = string;
export type Confidence = number;
export type Timestamp1 = string;
export type DataCompleteness = number;
export type QualityScore = number;
/**
 * Status throughout the ingestion workflow
 */
export type IngestionStatus1 = 'harvested' | 'enriched' | 'validated' | 'approved' | 'rejected' | 'archived';
export type ValidationErrors = string[];
export type ValidationWarnings = string[];

/**
 * UNIFIED PRODUCT MODEL (v6.0 - Strict Separation): Single source of separation.
 *
 * This model enforces the "Iron Rules" of source-of-truth:
 * 1. COMMERCIAL (Halilit) -> Inventory, Price, SKU (The Golden List)
 * 2. OFFICIAL (Brand) -> Specs, Media, Description (The Knowledge)
 * 3. CONTEXTUAL (Reviews) -> Ratings, Pros/Cons (The Insight)
 */
export interface IngestionProductDraft {
  halilit_id: HalilitId;
  product_name: ProductName;
  brand: Brand;
  price_il: PriceIl;
  price_eilat: PriceEilat;
  halilit_url: HalilitUrl;
  sku?: Sku;
  model_number?: ModelNumber;
  official_name?: OfficialName;
  official_specs?: OfficialSpecs;
  official_description?: OfficialDescription;
  official_images?: OfficialImages;
  official_url?: OfficialUrl;
  reviews?: Reviews;
  review_synthesis?: ReviewSynthesis;
  average_rating?: AverageRating;
  status?: IngestionStatus;
  pipeline_phase?: PipelinePhase;
  created_at?: CreatedAt;
  last_updated?: LastUpdated;
  taxonomy?: TaxonomyMapping | null;
  pricing?: PricingData | null;
  display?: DisplayProperties | null;
  specifications?: ProductSpecifications | null;
  description_short?: DescriptionShort;
  description_long?: DescriptionLong;
  feature_list?: FeatureList;
  sources?: Sources;
  primary_source?: SourceProvenance | null;
  lineage?: Lineage;
  raw_snapshot?: RawSnapshot;
  data_completeness?: DataCompleteness;
  quality_score?: QualityScore;
  validation_status?: IngestionStatus1;
  validation_errors?: ValidationErrors;
  validation_warnings?: ValidationWarnings;
  [k: string]: unknown;
}
/**
 * Tech specs from brand site
 */
export interface OfficialSpecs {
  [k: string]: unknown;
}
/**
 * Individual media asset with purpose
 */
export interface MediaAsset {
  type: Type;
  url: Url;
  display_purpose: DisplayPurpose;
  resolution?: Resolution;
  source?: DataSourceConfidence;
  alt_text?: AltText;
  priority?: Priority;
  [k: string]: unknown;
}
/**
 * Product's position in taxonomy hierarchy
 */
export interface TaxonomyMapping {
  canonical_category: CanonicalCategory;
  canonical_subcategory: CanonicalSubcategory;
  brand_taxonomy?: BrandTaxonomy;
  alt_categories?: AltCategories;
  keywords?: Keywords;
  [k: string]: unknown;
}
/**
 * All pricing information in one place
 */
export interface PricingData {
  price_il: PriceIl1;
  price_eilat: PriceEilat1;
  price_usd?: PriceUsd;
  price_eur?: PriceEur;
  tier?: PricingTier;
  eilat_discount_percent?: EilatDiscountPercent;
  suggested_tier?: PricingTier1 | null;
  price_validity_marker?: PriceValidityMarker;
  last_price_change?: LastPriceChange;
  previous_price_il?: PreviousPriceIl;
  [k: string]: unknown;
}
/**
 * How product should be displayed in UI
 */
export interface DisplayProperties {
  display_role?: DisplayRole;
  hero_image?: HeroImage;
  thumbnail_image?: ThumbnailImage;
  should_highlight?: ShouldHighlight;
  display_tier_level?: DisplayTierLevel;
  color_hint?: ColorHint;
  media_assets?: MediaAssets;
  [k: string]: unknown;
}
/**
 * Technical specifications with source tracking
 */
export interface ProductSpecifications {
  specs_dict?: SpecsDict;
  specs_source?: DataSourceConfidence1;
  specs_completeness?: SpecsCompleteness;
  specs_markdown?: SpecsMarkdown;
  [k: string]: unknown;
}
export interface SpecsDict {
  [k: string]: unknown;
}
/**
 * Track where data came from and its quality
 */
export interface SourceProvenance {
  source_name: SourceName;
  source_url: SourceUrl;
  confidence?: DataSourceConfidence2;
  timestamp?: Timestamp;
  extraction_method: ExtractionMethod;
  extraction_notes?: ExtractionNotes;
  [k: string]: unknown;
}
/**
 * Per-field data lineage tracking
 */
export interface Lineage {
  [k: string]: FieldLineage;
}
/**
 * Track provenance of specific data fields
 */
export interface FieldLineage {
  field_name: FieldName;
  source: Source;
  confidence: Confidence;
  timestamp?: Timestamp1;
  previous_value?: PreviousValue;
  [k: string]: unknown;
}
export interface PreviousValue {
  [k: string]: unknown;
}
/**
 * Snapshot of raw input data for verification
 */
export interface RawSnapshot {
  [k: string]: unknown;
}
